services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: checksPass
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_FORWARD_HEADERS_STRATEGY
        value: framework
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
